#!/bin/sh
set -e

DKMS_NAME=saa716x
DKMS_VERSION=0.4

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
#         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION
         rm -f /usr/share/doc/${DKMS_NAME}-dkms/${DKMS_NAME}*.log
      fi
    ;;
esac

exit 0
