#!/bin/sh
set -e

DKMS_NAME=saa716x
DKMS_VERSION=0.3

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac

exit 0
